// Shared spot data — FoilSpots Antwerp (BE/NL/FR day-trip spots, ≤2h from Berchem or Tervuren)
// Same schema as the Sydney site's spots-data.js, plus a `station` field per spot pointing at the
// nearest genuine on-water wind sensor (used for the live "on the water now" reading and for the
// auto-calibration script that derives `adj`). area: 'nl' | 'be' | 'fr'.
// adj:0 everywhere until the calibration script has enough history to compute real offsets.

const SPOTS = [
  { id:'brouwersdam-lake', name:'Brouwersdam (lake side)', area:'nl', water:'flat', skill:'beginner',
    lat:51.7430, lon:3.8480, adj:0, vc:247, vt:45, drive:'1h 50m from Berchem',
    station:{ network:'rws', code:'GRWI', label:'Grevelingensluis (RWS)' },
    desc:'Grevelingenmeer side of the dam — the main learning/freeride zone, protected from North Sea swell. Sweet spot 15–25 kn. Works well in SW/W; also rideable in N/NE. Low tide is shallow and flat, ideal for drills.',
    warnings:['Groynes and sandbars — stay inside the marked kite/wing zone between beach passages 14–17','Launch from the right (north) side of the main beach — do not launch in the swimming zone'],
    parking:{ type:'free', notes:'Large free parking lots on both sides of the dam, campervan-friendly.' },
    notes:'Lake side of Brouwersdam. Go-to SW/W spot. KBC Wingfoil Camp on site.' },
  { id:'brouwersdam-sea', name:'Brouwersdam (sea side)', area:'nl', water:'wave', skill:'advanced',
    lat:51.7390, lon:3.8420, adj:0, vc:270, vt:45, drive:'1h 50m from Berchem',
    station:{ network:'rws', code:null, label:'nearest RWS North Sea coastal station — to confirm' },
    desc:'North Sea side of the dam — cleaner in SW/NW, advanced wave riding. At high tide the water can flood the beach into a rare shallow flat lagoon for a couple of hours.',
    warnings:['Strong tidal current on the North Sea side','Groynes — know where the marked zone ends'],
    parking:{ type:'free', notes:'Large free parking lots on both sides of the dam, campervan-friendly.' },
    notes:'Sea side of Brouwersdam. Advanced only — waves. Same parking as lake side.' },
  { id:'veerse-meer', name:'Veerse Meer (Vrouwenpolder)', area:'nl', water:'flat', skill:'beginner',
    lat:51.5808, lon:3.6923, adj:0, vc:0, vt:180, drive:'1h 35m from Berchem',
    station:{ network:'rws', code:null, label:'nearest RWS Veerse Meer / Oosterschelde station — to confirm' },
    desc:'Sheltered inland sea, protected from North Sea swell in all conditions — works in any wind direction. Wind typically 3–5 kn lighter than the coast. The safest fallback spot in the region.',
    warnings:['Oyster banks throughout the lake bed — booties or shoes are not optional'],
    parking:{ type:'paid', notes:'~€3.50/day at the main lots (Vrouwenpolder, second bridge).' },
    notes:'All-directions safe haven. Vertigo Sports and Wingfoil en Zeeland operate here.' },
  { id:'oesterdam', name:'Oesterdam Westzijde', area:'nl', water:'flat', skill:'beginner',
    lat:51.5215, lon:4.1971, adj:0, vc:0, vt:170, drive:'45 min from Berchem',
    station:{ network:'rws', code:null, label:'nearest RWS Oosterschelde station — to confirm' },
    desc:'Sheltered bay on the Oosterschelde side of the Oesterdam. Closest flat-water spot to Antwerp — viable for an after-work session. Works in almost any direction including E/NE, when the open coast is offshore.',
    warnings:['Mild tidal current — still check the tide table'],
    parking:{ type:'free', notes:'Free, ample parking directly at the spot.' },
    notes:'Closest flat-water spot to home. Oesterdam Boardriders Club (OBC) on site.' },
  { id:'oostende', name:'Oostende', area:'be', water:'wave', skill:'intermediate',
    lat:51.2278, lon:2.9166, adj:0, vc:247, vt:45, drive:'1h 10m from Berchem',
    station:{ network:'mvb', code:null, label:'Meetnet Vlaamse Banken — Oostende meetpaal (to confirm exact station ID)' },
    desc:'Main Belgian coast city spot — open North Sea beach. Chop to small/medium waves depending on wind and tide. Not a primary learning spot; good for feeling real North Sea conditions.',
    warnings:['Groynes everywhere on the Belgian coast — hard and sharp, dangerous in a downwind drift','Shipping traffic offshore — this is a working port','Avoid E and NE — can be offshore depending on exact beach orientation'],
    parking:{ type:'paid', notes:'Along Koningin Astridlaan — scarce in summer; overflow at Thermae Palace.' },
    notes:'Roze Villa (western end) is the safest launch, works even in slightly cross-offshore wind.' },
  { id:'knokke-cadzand', name:'Knokke-Heist / Cadzand-Bad', area:'be', water:'wave', skill:'intermediate',
    lat:51.3700, lon:3.3900, adj:0, vc:270, vt:45, drive:'55 min from Berchem',
    station:{ network:'mvb', code:null, label:'Meetnet Vlaamse Banken — Wandelaar (nearest buoy, to confirm)' },
    desc:'Closest open-coast spot from Antwerp. Beach faces roughly NW, so NW is side-shore (ideal). Choppy in light wind, building to 1–2m waves once it’s really blowing.',
    warnings:['Groynes — same hazard as Oostende','Tide-dependent sandbanks can create strong currents'],
    parking:{ type:'paid', notes:'Knokke: near Zwinlaan. Cadzand: paid, in the village.' },
    notes:'Surfers Paradise (Knokke, BE side) has confirmed long-term board storage.' },
  { id:'de-panne', name:'De Panne', area:'be', water:'wave', skill:'advanced',
    lat:51.0937, lon:2.5836, adj:0, vc:270, vt:60, drive:'1h 25m from Berchem',
    station:{ network:'mvb', code:null, label:'Meetnet Vlaamse Banken — Nieuwpoort Buoy (to confirm)' },
    desc:'Southernmost Belgian beach spot, near the French border. A slight turn in the coastline gives S a partial side-shore option. Open coast — not a spot for learning.',
    warnings:['Groynes','Limited flat water','Strong current'],
    parking:{ type:'paid', notes:'Plenty of parking, some paid.' },
    notes:'Mostly for experienced riders wanting waves. Consider Bray-Dunes as a wider-window alternative nearby.' },
  { id:'bray-dunes', name:'Bray-Dunes / Dunkirk (FR)', area:'fr', water:'wave', skill:'intermediate',
    lat:51.0765, lon:2.5175, adj:0, vc:280, vt:70, drive:'1h 35m from Berchem',
    station:{ network:'mvb', code:null, label:'No BE/NL network reaches French waters — using MVB Nieuwpoort Buoy (~15km) as the nearest on-water proxy' },
    desc:'A 9-mile sandy beach running from Dunkirk to Bray-Dunes, just inside France. Faces almost due north — W is side-shore, giving a wide wind window. Wind runs consistently ~5 kn stronger than forecast here (funnel effect along the dunes).',
    warnings:['Never ride in E or NE — offshore into the North Sea','High tide leaves very little beach — cramped launch conditions','Tidal currents in the water'],
    parking:{ type:'free', notes:'Direct beachfront parking at the Station Nautique (Digue Nicolas II).' },
    notes:'Dunkerque Flysurfing Club (DFC) on site. Best at low tide — wide beach, flat water, more space.' }
];
